version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-30
        environment:
          JAVA_OPTS: -Xmx1536m
          GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx1536m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - run:
          name: add fontconfig for easylauncher
          command: sudo apt-get update && sudo apt-get install -y fontconfig fonts-ipafont
      - run:
          name: output local.properties(no data)
          command: echo > local.properties
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: jars-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
      - run:
          name: output google-services.json(dev)
          command: cp app/google-services.json.dev app/google-services.json
      - run:
          name: Test
          command: ./gradlew --stacktrace testDebugUnitTest
      - run:
          name: Build
          command: ./gradlew --stacktrace assembleDebug appDistributionUploadDebug
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk

# workaround for tag trigger
# because workflow git tag trigger does not work well
deployment:
  fake_for_deploy:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"
